package com.smartgoal.dao;

import com.smartgoal.model.Notification;
import com.smartgoal.util.DBConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class NotificationDAO {

    public NotificationDAO() {
        ensureTableExists();
    }

    private void ensureTableExists() {
        String sql = "BEGIN " +
                     "   EXECUTE IMMEDIATE 'CREATE TABLE notifications (" +
                     "       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                     "       user_id NUMBER REFERENCES users(id) ON DELETE CASCADE, " +
                     "       message VARCHAR2(500) NOT NULL, " +
                     "       is_read NUMBER(1) DEFAULT 0, " +
                     "       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                     "   )'; " +
                     "EXCEPTION WHEN OTHERS THEN NULL; END;";
        try (Connection con = DBConnection.getConnection();
             Statement st = con.createStatement()) {
            st.execute(sql);
        } catch (SQLException e) {
            // Table probably already exists
        }
    }

    public boolean addNotification(int userId, String message) {
        String sql = "INSERT INTO notifications (user_id, message) VALUES (?, ?)";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, userId);
            ps.setString(2, message);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    public List<Notification> getNotificationsByUser(int userId) {
        List<Notification> list = new ArrayList<>();
        String sql = "SELECT * FROM notifications WHERE user_id = ? ORDER BY created_at DESC FETCH FIRST 10 ROWS ONLY";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, userId);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Notification n = new Notification();
                n.setId(rs.getInt("id"));
                n.setUserId(rs.getInt("user_id"));
                n.setMessage(rs.getString("message"));
                n.setIsRead(rs.getInt("is_read"));
                n.setCreatedAt(rs.getTimestamp("created_at").toString());
                n.setTimeAgo(formatTimeAgo(rs.getTimestamp("created_at")));
                list.add(n);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    public boolean markAsRead(int notificationId) {
        String sql = "UPDATE notifications SET is_read = 1 WHERE id = ?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, notificationId);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    private String formatTimeAgo(Timestamp ts) {
        long diff = System.currentTimeMillis() - ts.getTime();
        long minutes = diff / (1000 * 60);
        if (minutes < 1) return "Just now";
        if (minutes < 60) return minutes + "m ago";
        long hours = minutes / 60;
        if (hours < 24) return hours + "h ago";
        return (hours / 24) + "d ago";
    }
}
