-- ============================================================
--   Smart Goal Management System — Database Schema (Oracle)
-- ============================================================
SET DEFINE OFF;


-- Note: You should run this in your Oracle SQL Developer or VS Code Oracle Extension
-- Connected as a user with table creation privileges (e.g., system or a specific schema user)

-- --------------------------------------------------------
-- Drop existing tables to ensure a clean run
-- --------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE progress CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE assignments CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE goals CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- --------------------------------------------------------
-- Table: users
-- --------------------------------------------------------
CREATE TABLE users (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(100) NOT NULL,
    email      VARCHAR2(150) NOT NULL UNIQUE,
    password   VARCHAR2(255) NOT NULL,
    role       VARCHAR2(20) DEFAULT 'employee' NOT NULL CHECK (role IN ('employee','manager')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------
-- Table: goals
-- --------------------------------------------------------
CREATE TABLE goals (
    goal_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER NOT NULL,
    title       VARCHAR2(200) NOT NULL,
    description CLOB,
    deadline    DATE,
    status      VARCHAR2(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending','in_progress','completed')),
    priority    VARCHAR2(20) DEFAULT 'medium' NOT NULL CHECK (priority IN ('low','medium','high')),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- --------------------------------------------------------
-- Table: assignments
-- --------------------------------------------------------
CREATE TABLE assignments (
    assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id    NUMBER NOT NULL,
    employee_id   NUMBER NOT NULL,
    task          CLOB NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assign_manager FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_assign_employee FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE CASCADE
);

-- --------------------------------------------------------
-- Table: progress
-- --------------------------------------------------------
CREATE TABLE progress (
    progress_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id     NUMBER NOT NULL,
    status      VARCHAR2(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending','in_progress','completed')),
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prog_goal FOREIGN KEY (goal_id) REFERENCES goals(goal_id) ON DELETE CASCADE
);

-- Trigger to update 'updated_at' on progress table automatically
CREATE OR REPLACE TRIGGER trg_progress_updated
BEFORE UPDATE ON progress
FOR EACH ROW
BEGIN
   :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================
--   Sample Data
-- ============================================================

-- Sample users (password: admin123)
INSERT INTO users (name, email, password, role) VALUES ('Alice Manager', 'alice@company.com', 'admin123', 'manager');
INSERT INTO users (name, email, password, role) VALUES ('Bob Employee', 'bob@company.com', 'admin123', 'employee');
INSERT INTO users (name, email, password, role) VALUES ('Carol Employee', 'carol@company.com', 'admin123', 'employee');

-- Sample goals
INSERT INTO goals (user_id, title, description, deadline, status, priority) VALUES (2, 'Learn Java Servlets', 'Complete servlet tutorial and build a project', TO_DATE('2026-06-01', 'YYYY-MM-DD'), 'in_progress', 'high');
INSERT INTO goals (user_id, title, description, deadline, status, priority) VALUES (2, 'Complete DBMS Course', 'Finish all modules and pass assessment', TO_DATE('2026-05-30', 'YYYY-MM-DD'), 'pending', 'medium');
INSERT INTO goals (user_id, title, description, deadline, status, priority) VALUES (3, 'Master HTML and CSS', 'Build 3 responsive websites', TO_DATE('2026-06-15', 'YYYY-MM-DD'), 'completed', 'low');

-- Sample assignments
INSERT INTO assignments (manager_id, employee_id, task) VALUES (1, 2, 'Review Q3 performance goals and submit a summary.');
INSERT INTO assignments (manager_id, employee_id, task) VALUES (1, 3, 'Prepare the updated presentation slides for the client meeting.');

-- Sample progress
INSERT INTO progress (goal_id, status) VALUES (1, 'in_progress');
INSERT INTO progress (goal_id, status) VALUES (2, 'pending');
INSERT INTO progress (goal_id, status) VALUES (3, 'completed');

-- Table: milestones
-- Stores sub-tasks for each goal
CREATE TABLE milestones (
    milestone_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id NUMBER REFERENCES goals(goal_id) ON DELETE CASCADE,
    description VARCHAR2(255) NOT NULL,
    is_completed NUMBER(1) DEFAULT 0 -- 0: Pending, 1: Completed
);

-- Sample Milestones
INSERT INTO milestones (goal_id, description, is_completed) VALUES (1, 'Finish homepage design', 1);
INSERT INTO milestones (goal_id, description, is_completed) VALUES (1, 'Connect to database', 0);
INSERT INTO milestones (goal_id, description, is_completed) VALUES (2, 'Read Chapter 1', 1);
INSERT INTO milestones (goal_id, description, is_completed) VALUES (2, 'Solve 10 problems', 0);

COMMIT;

